# Generated by Django 5.1.1 on 2024-10-15 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loginid', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[\\W_])[A-Z\\w\\W_]{6,}$')])),
                ('mobile', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(default='waiting', max_length=100)),
            ],
        ),
    ]
